export const personal = {
  name: "Akmal Bintang Budiawan",
  tagline: "Software Engineer",
  subtitle: "Building clean, purposeful software.",
  description:
    "A dedicated Software Developer bridging the gap between robust backend services and modern user interfaces. I specialize in the Next.js & .NET ecosystems, with a heavy focus on high-quality delivery and scalable software architecture.",
  location: "Jakarta, Indonesia",
  email: "akmalbintang33@gmail.com",
  github: "https://github.com/Twook21",
  linkedin: "https://www.linkedin.com/in/akmal-bintang-budiawan",
  instagram: "https://www.instagram.com/tw0ok_/", // Placeholder
  status: "Open to opportunities",
  philosophy: "Driven by impact, defined by adaptability",
  goal: "Expert Software Engineer · International Tech Ecosystem 2031",
};

export const experiences = [
  {
    id: "bifarma",
    role: "Full-Stack Developer",
    company: "PT Bifarma Adiluhung",
    parent: "Kalbe Group IT Hub",
    period: "Mar 2026 — Present",
    location: "Pulogadung, East Jakarta",
    type: "Internship",
    highlight: true,
    logo: "/logo-experience/bfa.png",
    description: "Architecting and scaling enterprise-level financial ecosystems across Kalbe Group subsidiaries (KDNA, PML, SCI, and Bifarma).",
    projects: [
      {
        name: "Enterprise Architecture",
        tech: ".NET / Oracle SQL",
        impact: "Engineered high-performance backend services and APIs to power complex financial workflows and ensure seamless data integration.",
      },
      {
        name: "UI/UX Modernization",
        tech: "Next.js / Blazor",
        impact: "Migrated legacy dashboards to fluid, mobile-responsive interfaces, drastically reducing user friction and improving navigation.",
      },
      {
        name: "Quality-Driven Delivery",
        tech: "Clean Code / Jest",
        impact: "Enforced strict Clean Code and ESLint standards, utilizing Jest for unit testing to guarantee high release confidence across parallel projects.",
      },
      {
        name: "System Stability",
        tech: "Auth & Session",
        impact: "Resolved critical session management and authentication bottlenecks, ensuring zero-downtime and robust security for enterprise users.",
      },
    ],
    tags: [".NET Core", "Oracle SQL", "Next.js", "Blazor", "Jest", "Clean Code", "ESLint"],
  },
  {
    id: "sci",
    role: "Front-End Developer",
    company: "Stem Cell and Cancer Institute (SCI)",
    parent: "Kalbe Farma Tbk",
    period: "Sep 2025 — Mar 2026",
    location: "Pulomas, East Jakarta",
    type: "Internship",
    highlight: false,
    logo: "/logo-experience/sci.png",
    description: "Engineered high-performance web platforms to process and visualize complex healthcare research data for multi-divisional teams.",
    projects: [
      {
        name: "Integrated R&D Platform",
        tech: "Next.js 15 / Redux",
        impact: "Built a robust data management application utilizing Tailwind CSS and Shadcn UI to streamline complex research operations.",
      },
      {
        name: "Scalable Architecture",
        tech: "Modular Design",
        impact: "Designed a feature-based, modular architecture to ensure the frontend codebase remains scalable and highly maintainable long-term.",
      },
      {
        name: "High-Density Visualization",
        tech: "TanStack Table",
        impact: "Leveraged TanStack Table to transform massive biological datasets into interactive, highly efficient analytical dashboards.",
      },
      {
        name: "Cross-Functional Integration",
        tech: "SCI & Kalgen DNA",
        impact: "Collaborated tightly with cross-functional teams to unify research, QA, and production workflows into a single digital ecosystem.",
      },
    ],
    tags: ["Next.js 15", "TypeScript", "Tailwind CSS", "Redux", "TanStack Table"],
  },
  {
    id: "dicoding",
    role: "Full‑Stack Web Developer Trainee",
    company: "Asah led by Dicoding",
    parent: "Accenture Collaboration",
    period: "Aug 2025 — 2026",
    location: "Remote",
    type: "Trainee",
    highlight: false,
    logo: "/logo-experience/asah.png",
    description: "Proficient in modern JavaScript stacks and integrated AI/Cloud fundamentals in an intensive, industry-aligned engineering path.",
    projects: [
      {
        name: "AI-Integrated Architecture",
        tech: "Front-End & Back-End",
        impact: "Completed a rigorous learning path focused on integrating AI capabilities into scalable backend systems, mentored by Accenture.",
      },
      {
        name: "Modern JS Ecosystem",
        tech: "Node.js",
        impact: "Built and deployed robust web components leveraging modern JavaScript tools and Cloud infrastructure best practices.",
      },
    ],
    tags: ["Node.js", "Git", "JavaScript", "AI", "Cloud"],
  },
  {
    id: "sanbercode",
    role: "React.js Developer Trainee",
    company: "Sanbercode",
    parent: "Intensive Program",
    period: "Dec 2025",
    location: "Remote",
    type: "Trainee",
    highlight: false,
    logo: "/logo-experience/sanbercode.png",
    description: "Proficient in component-driven UI development and dynamic state management through an intensive, project-based engineering program.",
    projects: [
      {
        name: "Component Architecture",
        tech: "React.js",
        impact: "Built interactive, reusable UI components focusing on modularity, clean rendering, and maintainable frontend architecture.",
      },
      {
        name: "Dynamic State Management",
        tech: "Hooks & API",
        impact: "Implemented efficient data fetching and state management logic to build highly responsive, dynamic web applications.",
      },
    ],
    tags: ["React.js", "JavaScript", "Hooks", "REST API"],
  },
  {
    id: "jabar-digital",
    role: "Full‑Stack Web Developer Trainee",
    company: "Jabar Istimewa Digital Academy",
    parent: "BNSP Certification",
    period: "Mar 2025 — Aug 2025",
    location: "Remote",
    type: "Trainee",
    highlight: false,
    logo: "/logo-experience/jida.png",
    description: "Solidified scalable application fundamentals, culminating in formal competency recognition as a certified web programmer.",
    projects: [
      {
        name: "Project-Based Engineering",
        tech: "Full-Stack Program",
        impact: "Proficient in full-stack web development fundamentals through structured, industry-oriented technical assessments.",
      },
      {
        name: "Competency Recognition",
        tech: "BNSP Certification",
        impact: "Earned formal industry recognition and official certification as a BNSP Web Junior Programmer.",
      },
    ],
    tags: ["JavaScript", "TypeScript", "BNSP", "Fullstack"],
  },
  {
    id: "pgri",
    role: "Full-Stack Web Developer",
    company: "PGRI Education Foundation",
    parent: "Education Sector",
    period: "Oct 2024 — Aug 2025",
    location: "Bandung, West Java",
    type: "Internship",
    highlight: false,
    logo: "/logo-experience/pgri.png",
    description: "Led the digital transformation of internal operational workflows, laying a solid foundation in full-stack system design.",
    projects: [
      {
        name: "Workflow Automation",
        tech: "Laravel",
        impact: "Digitized internal operations by building end-to-end employee attendance and document tracking systems from scratch.",
      },
      {
        name: "Performance Optimization",
        tech: "System Maintenance",
        impact: "Maintained and optimized the main organizational website to ensure maximum uptime and a seamless user experience.",
      },
    ],
    tags: ["Laravel", "PHP", "MySQL", "Git"],
  },
];

export const projects = [
  {
    id: "telcorecs",
    name: "TELCORECS",
    tagline: "B2B AI Recommendation Engine",
    description: "An AI-powered B2B recommendation system for telecom companies to reduce churn rates and improve product offerings through personalized customer targeting.",
    status: "Shipped",
    statusColor: "blue",
    period: "2026",
    tags: ["Next.js", "Redux", "Express.js", "Python", "AI / ML"],
    highlights: [
      "Architected scalable frontend infrastructure with Next.js & Redux",
      "Converted complex design requirements into modular React components",
      "Integrated machine learning APIs for user data processing",
      "Delivered personalized recommendations with 90% accuracy",
    ],
    github: null,
    demo: "http://telco-six.vercel.app/",
    image: "/projects/telcorecs.png",
    associatedWith: "ASAH",
    associatedLogo: "/logo-experience/asah.png",
    size: "large",
  },
  {
    id: "nomi",
    name: "NOMI",
    tagline: "Food Waste Reduction Platform",
    description: "A full-stack marketplace connecting F&B businesses with local communities to monetize near-expiry food inventory and reduce waste.",
    status: "Shipped",
    statusColor: "blue",
    period: "2025",
    tags: ["Next.js", "PostgreSQL", "Tailwind CSS", "ESLint"],
    highlights: [
      "Engineered full-stack marketplace for surplus inventory",
      "Designed robust backend APIs via PostgreSQL for secure transactions",
      "Built responsive, dynamic frontend interface with Next.js",
      "Meticulously clean, linted code adhering to ESLint standards",
    ],
    github: null,
    demo: "https://nomi-antiwastefood.vercel.app/",
    image: "/projects/nomi.png",
    associatedWith: "Jabar Digital Academy",
    associatedLogo: "/logo-experience/jida.png",
    size: "wide",
  },
  {
    id: "pgri-finance",
    name: "PGRI Education Foundation Finance",
    tagline: "Centralized Financial Ecosystem",
    description: "A robust, centralized financial management platform designed to consolidate reports across dispersed regional branches, replacing manual workflows.",
    status: "Shipped",
    statusColor: "blue",
    period: "2025",
    tags: ["Laravel", "Filament", "MySQL", "RBAC"],
    highlights: [
      "Built centralized financial management system via Laravel Filament",
      "Engineered secure RBAC architecture for branch data isolation",
      "Reduced cross-branch reporting time from hours to instant generation",
      "Optimized high-volume data handling and validation protocols",
    ],
    github: null,
    demo: null,
    image: "/projects/pgri-finance.png",
    associatedWith: "PGRI Education Foundation",
    associatedLogo: "/logo-experience/pgri.png",
    size: "tall",
  },
  {
    id: "fintap",
    name: "FinTap",
    tagline: "Geo-Verified Attendance System",
    description: "A custom attendance management system featuring geolocation tracking and face verification to eliminate proxy check-ins.",
    status: "Shipped",
    statusColor: "blue",
    period: "2025",
    tags: ["Laravel 11", "Tailwind CSS", "MySQL", "Geolocation"],
    highlights: [
      "Implemented optimized MySQL geolocation tracking & geofencing",
      "Integrated face verification to eliminate proxy attendance",
      "Achieved 90% verification accuracy rate",
      "Real-time analytics dashboard with anomaly detection",
    ],
    github: null,
    demo: null,
    image: "/projects/fintap.png",
    associatedWith: "PGRI Education Foundation",
    associatedLogo: "/logo-experience/pgri.png",
    size: "small",
  },
  {
    id: "wastego-project",
    name: "WasteGo",
    tagline: "Smart Waste Management Platform",
    description: "An environmental platform connecting households with waste collectors, scaled from a campus initiative to a robust community tool.",
    status: "Shipped",
    statusColor: "blue",
    period: "2025",
    tags: ["React.js", "Tailwind CSS", "UX/UI"],
    highlights: [
      "Architected frontend interface with React.js",
      "Translated complex user flows into responsive components",
      "Scaled platform from campus to community level",
    ],
    github: null,
    demo: "https://wastegosite.vercel.app/",
    image: "/projects/wastego.png",
    associatedWith: "EEPIS",
    associatedLogo: null,
    size: "small",
  },
  {
    id: "e-archive",
    name: "e-Archive",
    tagline: "Secure Document Management System",
    description: "A secure organizational archive system featuring dynamic folder hierarchies and role-based access restrictions.",
    status: "Shipped",
    statusColor: "blue",
    period: "2025",
    tags: ["Laravel 11", "MySQL", "Full-Text Search"],
    highlights: [
      "Custom .dcx template engine",
      "Optimized MySQL full-text search for fast retrieval",
      "Engineered secure role-based access restrictions",
    ],
    github: null,
    demo: null,
    image: "/projects/e-archive.png",
    associatedWith: "PGRI Education Foundation",
    associatedLogo: "/logo-experience/pgri.png",
    size: "wide",
  },
  {
    id: "yplp-portal",
    name: "YPLP PGRI Education Foundation West Java",
    tagline: "Official Web Portal",
    description: "A robust digital presence portal equipped with a custom Content Management System (CMS).",
    status: "Shipped",
    statusColor: "blue",
    period: "2024",
    tags: ["PHP", "MySQL", "CMS"],
    highlights: [
      "Developed custom Content Management System (CMS)",
      "Implemented strict input validation and session management",
      "Ensured maximum uptime and data safety",
    ],
    github: null,
    demo: "https://perwakilanyplppgrijawabarat.com/",
    image: "/projects/pgri.png",
    associatedWith: "PGRI Education Foundation",
    associatedLogo: "/logo-experience/pgri.png",
    size: "tall",
  },
  {
    id: "jobsly",
    name: "Jobsly",
    tagline: "Job Portal Application",
    description: "A dynamic job vacancy interface focusing on foundational React architecture and seamless single-page experience.",
    status: "Shipped",
    statusColor: "blue",
    period: "2024",
    tags: ["React.js", "React Router", "State Management"],
    highlights: [
      "Implemented complex client-side routing",
      "Focus on modularity and foundational React architecture",
      "Seamless single-page application experience",
    ],
    github: null,
    demo: "https://jocular-alpaca-d526ba.netlify.app/",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=1000&auto=format&fit=crop",
    associatedWith: "Sanbercode",
    associatedLogo: "/logo-experience/sanbercode.png",
    size: "small",
  },
];

export const skills = {
  frontend: [
    { name: "Next.js", level: 90 },
    { name: "React", level: 90 },
    { name: "TypeScript", level: 85 },
    { name: "Tailwind CSS", level: 92 },
    { name: "Shadcn UI", level: 85 },
    { name: ".NET Blazor", level: 85 },
  ],
  backend: [
    { name: "ASP .NET Core (C#)", level: 72 },
    { name: "FastAPI", level: 68 },
    { name: "PostgreSQL", level: 70 },
    { name: "Oracle SQL", level: 65 },
  ],
  devops: [
    { name: "Git / GitHub", level: 88 },
    { name: "Docker", level: 68 },
    { name: "CI/CD", level: 72 },
    { name: "Ubuntu / Linux", level: 75 },
  ],
  testing: [
    { name: "Jest", level: 80 },
    { name: "Unit Testing", level: 78 },
    { name: "ESLint", level: 85 },
  ],
};

export const softSkills = [
  {
    title: "Growth Mindset",
    description:
      "Focusing on impact, not just frameworks. My journey spans from Laravel to Next.js and .NET. Actively learning Cloud & AI to tackle future challenges.",
    icon: "🌱",
  },
  {
    title: "Cross-Platform Adaptability",
    description:
      "Proven track record switching between .NET enterprise stacks and modern JS/React ecosystems without losing momentum.",
    icon: "⚡",
  },
  {
    title: "Challenge-Based Learning",
    description:
      "Solves real-world corporate problems independently in high-stakes healthcare environments at SCI/Kalbe.",
    icon: "🎯",
  },
  {
    title: "Minimalist Aesthetic",
    description:
      "Deeply values Human Interface Guidelines and purposeful design — reflected in every UI decision.",
    icon: "✦",
  },
  {
    title: "Quality Obsession",
    description:
      "Enforces strict ESLint, unit testing (Jest), and code review standards. 'Ship clean or don't ship.'",
    icon: "◎",
  },
  {
    title: "Async Collaboration",
    description:
      "Comfortable managing multiple concurrent projects (4 simultaneous) across distributed enterprise teams.",
    icon: "🔗",
  },
];

export const milestones = [
  {
    date: "Present",
    title: "Dicoding Developer Conference",
    description: "Exploring modern Cloud architecture and emerging AI development patterns to stay ahead of the curve.",
    tag: "Continuous Learning",
    color: "accent",
  },
  {
    date: "2026",
    title: "Architecting SmartAttendance",
    description: "Engineered an automated presence tracking system for an external institution as my final-year capstone project. Focused on streamlining real-world operational workflows and ensuring high-fidelity data integrity.",
    tag: "Capstone Engineering",
    color: "accent",
  },
  {
    date: "2025 — Present",
    title: "Advancing to Kalbe’s IT Center (Bifarma)",
    description: "Handpicked to transition from SCI to PT. Bifarma Adiluhung—Kalbe’s centralized IT hub. After successfully delivering multidisciplinary systems for R&D, QA, and Production divisions at SCI, I now engineer group-wide enterprise projects, scaling my expertise from Frontend to Full-Stack architecture.",
    tag: "Strategic Career Advancement",
    color: "orange",
  },
  {
    date: "2025 — 2026",
    title: "Advanced Full-Stack Trainee (Asah & JIDA)",
    description: "Sharpened technical rigor through industry-aligned programs: Asah (Dicoding x Accenture) focused on AI-integrated backend and Jabar Digital Academy (JIDA) for scalable web fundamentals.",
    tag: "Competency Mastery",
    color: "green",
  },
  {
    date: "2024 — 2025",
    title: "11-Month Fullstack Internship (PGRI Education Foundation)",
    description: "Shipped end-to-end internal web applications, establishing a strong baseline in full-stack development and operational systems.",
    tag: "Building the Foundation",
    color: "accent",
  },
  {
    date: "2024",
    title: "Laravel Training at Gema Foundation",
    description: "Transitioned from static interfaces to server-side logic. Completed an intensive program where I built my very first database-driven web application.",
    tag: "Entering the Dynamic Web",
    color: "accent",
  },
  {
    date: "2023",
    title: "My First <Hello World !>",
    description: "Initiated my software engineering journey during my first semester, mastering the core building blocks: HTML, CSS, and JavaScript.",
    tag: "The Starting Point",
    color: "green",
  },
];

export const certifications = [
  {
    name: "Certification",
    issuer: "— Coming Soon —",
    date: "",
    status: "upcoming",
    description:
      "Currently pursuing relevant certifications to strengthen the engineering profile.",
  },
];

export const moments = [
  {
    id: 1,
    title: "Jakarta Golden Hour",
    description: "The vibrant energy of the city where my enterprise engineering journey began.",
    image: "https://images.unsplash.com/photo-1555899434-94d1368aa7af?auto=format&fit=crop&q=80&w=800",
    size: "large", // 2x2 (Highlight Atas)
    category: "Life",
  },
  {
    id: 2, // Susunan diubah agar mengisi kolom kanan atas dengan sempurna
    title: "PENS Surabaya",
    description: "The academic foundation where my technical rigor was built.",
    image: "/moments/pens-campus.jpg",
    size: "tall", // 1x2
    category: "Education",
  },
  {
    id: 3,
    title: "BDD Conference",
    description: "Exploring modern web scaling, AWS Serverless, and Laravel in the AI era.",
    image: "/moments/bdd-conference.jpg",
    size: "tall", // 1x2
    category: "Conference",
  },
  {
    id: 4,
    title: "SCI Tech Family",
    description: "Cross-functional synergy. Celebrating milestones together as one united team.",
    image: "/moments/sci-birthday.jpg",
    size: "wide", // 2x1
    category: "Team",
  },
  {
    id: 5,
    title: "Microsoft METC",
    description: "Diving deep into Microsoft Fabric and Azure AI to navigate modern data architectures.",
    image: "/moments/microsoft-metc.jpg",
    size: "wide", // Diubah dari small ke wide (+1 unit agar total grid genap 20)
    category: "Engineering",
  },
  {
    id: 6,
    title: "DDC 2026",
    description: "Calibrating skills with emerging Cloud and AI patterns to stay ahead of the curve.",
    image: "/moments/dicoding-conf.jpg",
    size: "large", // 2x2 (Highlight Bawah)
    category: "Event",
  },
  {
    id: 7,
    title: "JIDA Graduation",
    description: "Earning the BNSP Junior Web Programmer certification. Proud to be among the final 50.",
    image: "/moments/jida-graduation.jpg",
    size: "wide", // 2x1
    category: "Achievement",
  },
  {
    id: 8,
    title: "Gema Foundation Gathering",
    description: "Educate to elevate",
    image: "/moments/gema.jpg",
    size: "small", // 1x1 (Menutup kolom kanan bawah)
    category: "Gathering",
  },
  {
    id: 9,
    title: "Always Calibrating",
    description: "Capturing a moment of personal growth and technical exploration.",
    image: "/moments/me.jpeg",
    size: "small", // 1x1 (Menutup kolom kanan bawah)
    category: "Personal",
  },
  {
    id: 10,
    title: "IT One Kalbe Gathering",
    description: "Unifying technology and talent across the Kalbe ecosystem.",
    image: "/moments/one-kalbe.jpg",
    size: "wide",
    category: "Team",
  },
  {
    id: 11,
    title: "MXperience Community",
    description: "Connecting with the Logitech MX community.",
    image: "/moments/mx-logitech.jpeg",
    size: "wide",
    category: "Community",
  },
];
